name: LaTeX to HTML

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build_all_latex:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      # TODO Igual puedes hacerlo de tal forma que ejecute en pandoc/latex solo la parte de pasar a html, y la que es pillar los archivos cambiados en normal
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # To retrieve the preceding commit for changed files
      - name: Compile to HTML all LaTeX
        run: |
          for file in `find -name '*.tex' -type f`; do
            echo -e "\x1b[1mCompiling $file\x1b[0m"
            pandoc "./${file}" -f latex -t html --katex
          done
      - run: pwd
      - name: Push HTML back to repo
        uses: actions-x/commit@v2
        with:
          message: Compiled LaTeX to HTML [job \#{{ env.GITHUB_JOB }}]
      # - run: git add prueba.html
      # - run: git commit -m "Compile prueba.html"
      # - run: git push
      # TODO https://github.community/t/find-what-files-changed-in-a-pushed-commit/17037 <- Maybe in GitHub works?
